-- PANZER V3 — Supabase / Postgres şeması
-- Supabase Dashboard → SQL Editor → bu dosyanın tamamını çalıştırın.
-- Ardından: npm run seed (panel satırı için)

CREATE TABLE IF NOT EXISTS kullanicilar (id BIGSERIAL PRIMARY KEY, kullaniciadi VARCHAR(100) UNIQUE NOT NULL, sifre VARCHAR(255) NOT NULL, tgkod VARCHAR(32), tgadresi VARCHAR(100) DEFAULT '', bakiye VARCHAR(50) DEFAULT '0', toplamalinan VARCHAR(50) DEFAULT '0', trxadresi VARCHAR(200) DEFAULT '', userimage VARCHAR(255) DEFAULT '', k_rol VARCHAR(20) DEFAULT '');
CREATE TABLE IF NOT EXISTS panel (id INT PRIMARY KEY DEFAULT 1, dom_panel VARCHAR(100) DEFAULT '', dom_sahibinden VARCHAR(100) DEFAULT '', dom_dolap VARCHAR(100) DEFAULT '', dom_letgo VARCHAR(100) DEFAULT '', dom_pttavm VARCHAR(100) DEFAULT '', dom_turkcell VARCHAR(100) DEFAULT '', dom_shopier VARCHAR(100) DEFAULT '', dom_yurtici VARCHAR(100) DEFAULT '', dom_facebook VARCHAR(100) DEFAULT '', dom_trendyol VARCHAR(100) DEFAULT '', dom_hepsiburada VARCHAR(100) DEFAULT '', dom_migros VARCHAR(100) DEFAULT '', dom_pasaj VARCHAR(100) DEFAULT '', dom_ptt3 VARCHAR(100) DEFAULT '', dom_bim VARCHAR(100) DEFAULT '', dom_a101 VARCHAR(100) DEFAULT '', dom_pttkargo VARCHAR(100) DEFAULT '', ibanad VARCHAR(200) DEFAULT '', iban VARCHAR(100) DEFAULT '', banka VARCHAR(100) DEFAULT '', adminbot_token VARCHAR(200) DEFAULT '', adminbot_chatid VARCHAR(100) DEFAULT '', cekimbot_token VARCHAR(200) DEFAULT '', cekimbot_chatid VARCHAR(100) DEFAULT '', dekontbot_token VARCHAR(200) DEFAULT '', dekontbot_chatid VARCHAR(100) DEFAULT '', vergibot_token VARCHAR(200) DEFAULT '', vergibot_chatid VARCHAR(100) DEFAULT '');
CREATE TABLE IF NOT EXISTS refkodlari (id BIGSERIAL PRIMARY KEY, ref_code VARCHAR(50) NOT NULL);
CREATE TABLE IF NOT EXISTS cekimtalepleri (id BIGSERIAL PRIMARY KEY, miktar VARCHAR(50), trxadresi VARCHAR(200), durum VARCHAR(50) DEFAULT 'Beklemede', tarih VARCHAR(20), saat VARCHAR(20), islemid VARCHAR(100), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS cekim_callbacks (unique_id VARCHAR(50) PRIMARY KEY, islemid VARCHAR(100), ekleyen VARCHAR(100), miktar VARCHAR(50), created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ilan_sahibinden (id BIGSERIAL PRIMARY KEY, ilandurum SMALLINT DEFAULT 1, urunadi VARCHAR(500), adsoyad VARCHAR(200), ilantarihi VARCHAR(50), ilanno VARCHAR(50), telno VARCHAR(50), urunfiyati VARCHAR(50), komisyon VARCHAR(50), aciklama TEXT, il VARCHAR(100), ilce VARCHAR(100), mahalle VARCHAR(200), kat1 VARCHAR(200), kat2 VARCHAR(200), kimden VARCHAR(100), durumu VARCHAR(100), kartibanselect VARCHAR(50), selectgiris VARCHAR(50), ozellik_ad TEXT, ozellik_deger TEXT, resim1 VARCHAR(255), resim2 VARCHAR(255), resim3 VARCHAR(255), resim4 VARCHAR(255), resim5 VARCHAR(255), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS ilan_dolap (id BIGSERIAL PRIMARY KEY, ilandurum SMALLINT DEFAULT 1, urunadi VARCHAR(500), adsoyad VARCHAR(200), urunfiyati VARCHAR(50), aciklama TEXT, kat1 VARCHAR(200), kat2 VARCHAR(200), kat3 VARCHAR(200), indirim VARCHAR(50), begeni VARCHAR(50), puan VARCHAR(50), yorum VARCHAR(50), alicisatici VARCHAR(50), kullanim VARCHAR(100), kartibanselect VARCHAR(50), selectgiris VARCHAR(50), resim1 VARCHAR(255), resim2 VARCHAR(255), resim3 VARCHAR(255), resim4 VARCHAR(255), resim5 VARCHAR(255), resim6 VARCHAR(255), saticipp VARCHAR(255), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS ilan_letgo (id BIGSERIAL PRIMARY KEY, ilandurum SMALLINT DEFAULT 1, urunadi VARCHAR(500), adsoyad VARCHAR(200), urunfiyati VARCHAR(50), ilantarihi VARCHAR(50), ilanno VARCHAR(50), aciklama TEXT, il VARCHAR(100), ilce VARCHAR(100), kat1 VARCHAR(200), kat2 VARCHAR(200), kategori1 VARCHAR(200), kategori2 VARCHAR(200), kategori3 VARCHAR(200), kategori4 VARCHAR(200), kartibanselect VARCHAR(50), selectgiris VARCHAR(50), resim1 VARCHAR(255), resim2 VARCHAR(255), resim3 VARCHAR(255), resim4 VARCHAR(255), resim5 VARCHAR(255), resim6 VARCHAR(255), saticipp VARCHAR(255), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS ilan_pttavm (id BIGSERIAL PRIMARY KEY, ilandurum SMALLINT DEFAULT 1, urunadi VARCHAR(500), urunfiyati VARCHAR(50), aciklama TEXT, kat1 VARCHAR(200), kat2 VARCHAR(200), kat3 VARCHAR(200), kartibanselect VARCHAR(50), selectgiris VARCHAR(50), resim1 VARCHAR(255), resim2 VARCHAR(255), resim3 VARCHAR(255), resim4 VARCHAR(255), resim5 VARCHAR(255), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS ilan_turkcell (id BIGSERIAL PRIMARY KEY, ilandurum SMALLINT DEFAULT 1, urunadi VARCHAR(500), urunfiyati VARCHAR(50), aciklama TEXT, kat1 VARCHAR(200), kat2 VARCHAR(200), kat3 VARCHAR(200), kartibanselect VARCHAR(50), selectgiris VARCHAR(50), resim1 VARCHAR(255), resim2 VARCHAR(255), resim3 VARCHAR(255), resim4 VARCHAR(255), resim5 VARCHAR(255), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS ilan_shopier (id BIGSERIAL PRIMARY KEY, ilandurum SMALLINT DEFAULT 1, urunadi VARCHAR(500), adsoyad VARCHAR(200), urunfiyati VARCHAR(50), aciklama TEXT, kat1 VARCHAR(200), kat2 VARCHAR(200), kat3 VARCHAR(200), kimden VARCHAR(100), durumu VARCHAR(100), kartibanselect VARCHAR(50), selectgiris VARCHAR(50), resim1 VARCHAR(255), resim2 VARCHAR(255), resim3 VARCHAR(255), resim4 VARCHAR(255), resim5 VARCHAR(255), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS profilshopier (id BIGSERIAL PRIMARY KEY, ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS yurtici (id BIGSERIAL PRIMARY KEY, ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS ty_ilan (id BIGSERIAL PRIMARY KEY, urunadi VARCHAR(500), saticiadi VARCHAR(200), urunaciklama TEXT, urunfiyat VARCHAR(50), urunkategori VARCHAR(200), urunresmi VARCHAR(255), kaynak_url VARCHAR(800), ilandurum VARCHAR(10) DEFAULT '1', ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS hb_urun (id BIGSERIAL PRIMARY KEY, urunlink VARCHAR(500), urunkategori VARCHAR(200), urunadi VARCHAR(500), urunfiyat VARCHAR(50), urunresim VARCHAR(255), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_mg_urunler (id BIGSERIAL PRIMARY KEY, urunismi VARCHAR(500), urunlink VARCHAR(300), urunkat VARCHAR(200), resim1 VARCHAR(255), resim2 VARCHAR(255), resim3 VARCHAR(255), resim4 VARCHAR(255), resim5 VARCHAR(255), fiyat VARCHAR(50), urunkodu VARCHAR(100), hakkinda TEXT, ozellik TEXT, iban VARCHAR(100), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_mg_banka (id SERIAL PRIMARY KEY, bankaisim VARCHAR(100), iban VARCHAR(100), ibanisim VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_pj_urunler (id BIGSERIAL PRIMARY KEY, urunismi VARCHAR(500), urunlink VARCHAR(300), fiyat VARCHAR(50), hakkinda TEXT, resim1 VARCHAR(255), resim2 VARCHAR(255), resim3 VARCHAR(255), resim4 VARCHAR(255), resim5 VARCHAR(255), kat1 VARCHAR(200), kat2 VARCHAR(200), kat3 VARCHAR(200), saticiadi VARCHAR(200), urunkodu VARCHAR(100), urunkat VARCHAR(200), ozellik TEXT, iban VARCHAR(100), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_pj_banka (id SERIAL PRIMARY KEY, bankaisim VARCHAR(100), iban VARCHAR(100), ibanisim VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_ptt3_urunler (id BIGSERIAL PRIMARY KEY, urunismi VARCHAR(500), urunlink VARCHAR(300), fiyat VARCHAR(50), hakkinda TEXT, resim1 VARCHAR(255), resim2 VARCHAR(255), resim3 VARCHAR(255), resim4 VARCHAR(255), resim5 VARCHAR(255), urunkat VARCHAR(200), urunkodu VARCHAR(100), ozellik TEXT, iban VARCHAR(100), ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_ptt3_banka (id SERIAL PRIMARY KEY, bankaisim VARCHAR(100), iban VARCHAR(100), ibanisim VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_bim_products (id BIGSERIAL PRIMARY KEY, "ProductName" VARCHAR(500), "ImageURL" VARCHAR(255), "ProductSefURL" VARCHAR(300), "ProductPrice" INT, "ProductProperties" TEXT, "ProductBrand" VARCHAR(200), "ProductCode" INT, ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_a101_products (id BIGSERIAL PRIMARY KEY, "ProductName" VARCHAR(500), "ImageURL" VARCHAR(255), "Image2URL" VARCHAR(255), "Image3URL" VARCHAR(255), "Image4URL" VARCHAR(255), "ProductSefURL" VARCHAR(300), "ProductPrice" INT, "ProductProperties" TEXT, "ProductBrand" VARCHAR(200), "ProductCode" INT, ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_a101_banks (id SERIAL PRIMARY KEY, bank_name VARCHAR(100), iban VARCHAR(100), name_surname VARCHAR(100));
CREATE TABLE IF NOT EXISTS bella_pttkargo (id BIGSERIAL PRIMARY KEY, takipno VARCHAR(32) UNIQUE, gonderen VARCHAR(200), teslimalan VARCHAR(200), cikistarih VARCHAR(50), teslimtarih VARCHAR(50), cikisadres TEXT, teslimadres TEXT, telefonno VARCHAR(30), gonderil VARCHAR(100), alanil VARCHAR(100), sonuc VARCHAR(200), durumu SMALLINT DEFAULT 1, ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS hesaplar (id BIGSERIAL PRIMARY KEY, ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS girisyapanlar (id BIGSERIAL PRIMARY KEY, ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS kartlar (id BIGSERIAL PRIMARY KEY, ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS ilan_facebook (id BIGSERIAL PRIMARY KEY, ekleyen VARCHAR(100));
CREATE TABLE IF NOT EXISTS ilceler (il VARCHAR(100), ilce VARCHAR(100));
